# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Finger1_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
    max_acceleration: 10.0

  Finger2_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
    max_acceleration: 10.0

  Seg1_link_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
    max_acceleration: 10.0

  Seg2_link_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
    max_acceleration: 10.0

  Seg3_link_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
    max_acceleration: 10.0
    
  Seg4_link_joint:
    has_velocity_limits: true
    has_acceleration_limits: true
    max_acceleration: 10.0