# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - Seg1_link_joint
      - Seg2_link_joint
      - Seg3_link_joint
      - Seg4_link_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - Finger1_joint
      - Finger2_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true